// Real Chromium interaction tests. Run from repository root with Playwright on NODE_PATH.
// Each case uses a fresh, non-persistent browser context. Production APIs are never called.
const {chromium}=require('playwright');
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const cases=JSON.parse(fs.readFileSync('03_Kiem_thu/QA_QC/phase2/qa_cases.json','utf8'));
const out=process.env.MINGO_QA_OUTPUT||'03_Kiem_thu/QA_QC/phase2/evidence/verification_runs/'+new Date().toISOString().replace(/[:.]/g,'-')+'/browser';fs.mkdirSync(out,{recursive:true});
const tests={};const add=(ids,fn)=>ids.split(' ').forEach(id=>tests[id]=fn);
let page,context,log,extra;
const assert=(v,m)=>{if(!v)throw Error(m)};
const btn=n=>page.getByRole('button',{name:n,exact:true});
const click=async n=>{log.push('Click: '+n);await btn(n).click()};
const text=()=>page.locator('#app').innerText();
const has=async(...strings)=>{const t=await text();for(const s of strings)assert(t.includes(s),'Missing copy: '+s)};
const state=()=>page.evaluate(()=>window.__MINGO_TEST__.getState());
async function home(){await click('Start learning');await click('Skip for now');await click('Start without it');await click('Go to Home')}
async function begin(domain='vocabulary'){await home();if(domain==='vocabulary')await click('Start cycle');else{await click('Learn');await page.getByTestId('action-L-020-start-'+domain).click()}await click('Begin')}
async function answer(label){await click(label);await click('Submit');await click('Continue')}
async function retrieve(domain='vocabulary'){await begin(domain);await answer(domain==='grammar'?'She is a student.':'Hello');await click('Continue')}
async function checkStep(domain='vocabulary',hint=false){await retrieve(domain);if(hint)await click('Need a hint?');await answer(domain==='grammar'?'is':'I’m good, thanks.');await answer(domain==='grammar'?'They are classmates.':'Good morning!');await click('Start Check')}
async function summary(hint=false){await checkStep('vocabulary',hint);await answer('Nice to meet you too.')}
async function staff(to){await click('Staff');if(to)await click(to)}
async function editor(){await staff('Content');await click('Create draft')}
async function review(){await editor();await click('Submit for review')}
async function approve(){await review();assert(await btn('Approve').isDisabled(),'Unlicensed approval');await click('Open source & license');await click('Mark verified for prototype');await click('Approve')}
async function publish(){await approve();await click('Confirm publish')}
async function syncQueued(){await begin();await click('Simulate offline');await answer('Hello');await click('Simulate offline');await click('Continue');await answer('I’m good, thanks.');assert((await state()).syncState==='local_queued','Online submission bypassed acknowledgement');await click('Learner');await page.getByRole('button',{name:'Simulate offline',exact:true}).focus();/* no state mutation */await page.getByRole('button',{name:'No recommendation',exact:true}).click();await click('Profile');await click('Sync status')}
async function ax(){const session=await context.newCDPSession(page);const tree=await session.send('Accessibility.getFullAXTree');await session.detach();return tree.nodes.filter(n=>!n.ignored).map(n=>({role:n.role?.value,name:n.name?.value,properties:n.properties}))}
async function reflow(width,route='Home',zoom=false){await page.setViewportSize({width,height:1000});await home();if(route!=='Home')await click(route);if(zoom){await page.evaluate(()=>{const els=[...document.querySelectorAll('body,body *')];const sizes=els.map(e=>parseFloat(getComputedStyle(e).fontSize));els.forEach((e,i)=>e.style.fontSize=(sizes[i]*2)+'px')});log.push('200% text scaling: double each computed font size without scaling viewport')}const metrics=await page.evaluate(()=>({viewport:innerWidth,body:document.body.scrollWidth,doc:document.documentElement.scrollWidth,buttons:[...document.querySelectorAll('#app button')].filter(e=>e.getClientRects().length).map(e=>({text:e.textContent,w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height,right:e.getBoundingClientRect().right}))}));extra.push(metrics);assert(metrics.doc<=width+1,'Horizontal overflow '+JSON.stringify(metrics));assert(metrics.buttons.every(b=>b.right<=width+1&&b.w>0),'Action clipped');}

add('QA-NAV-001',async()=>{await home();assert(JSON.stringify(await page.locator('.bottom-nav button').allTextContents())===JSON.stringify(['Home','Learn','Course','Profile']),'IA differs')});
add('QA-NAV-002',async()=>{for(const action of ['Start learning','Continue','Start without it']){assert(await page.locator('.bottom-nav').count()===0,'Main nav on onboarding');await click(action)}await has('provisional')});
add('QA-NAV-003 QA-LRN-003 QA-BIZ-011',async()=>{await home();await has('Due for review','Basic greetings','About 5 min','Start cycle');await click('Start cycle');await has('Duration is a configurable product hypothesis','Due for review')});
add('QA-NAV-004',async()=>{await home();await click('Learn');await has('Review → Learn → Retrieve → Transfer → Check');assert(await page.locator('.domain-card').count()===3,'Missing representative domain');assert(!/infinite|endless feed/i.test(await text()),'Endless feed')});
add('QA-NAV-005',async()=>{await home();await click('Course');await has('Current','Due review','Locked · preview available','Complete the prerequisite first');assert(await btn('Practice').isEnabled(),'Current not actionable')});
add('QA-NAV-006 QA-BIZ-008',async()=>{await home();await click('Profile');await has('Vocabulary · Building','Listening · Needs more evidence','Goal','Daily target');assert(!/\d+%/.test(await text()),'Fake mastery percent')});
add('QA-NAV-007',async()=>{await staff();assert(JSON.stringify(await page.locator('.side-link').allTextContents())===JSON.stringify(['Dashboard','Learners','Content','Interventions','Analytics','Administration']),'Staff IA')});
add('QA-NAV-008',async()=>{await staff('Content');await has('Draft','Published','Review queue');assert(!(await page.locator('.side-link').allTextContents()).includes('Publishing'),'Publishing top-level')});
add('QA-LRN-001 QA-LRN-012 QA-BIZ-002 QA-BIZ-010',async()=>{await summary();await has('Done for now','You practiced','Evidence context','Mingo needs repeated evidence','Continue learning');assert(await btn('Done for now').isEnabled(),'No explicit exit');assert(!/\d+%|mastered|reward unlocked/i.test(await text()),'Unsupported reward/mastery');await click('Done for now');await has('Ready for a short cycle?')});
add('QA-LRN-002',async()=>{await begin();await has('2 of 8');await answer('Hello');await has('3 of 8');await click('Continue');await has('4 of 8');assert(await page.locator('.progress span').count()===1,'No finite progress')});
add('QA-LRN-004',async()=>{await begin();await answer('Hello');await has('Learn','How are you?');assert(!/mastered/i.test(await text()),'Viewing implies mastery')});
add('QA-LRN-005 QA-BIZ-001',async()=>{await retrieve();const before=await state();await click('I’m good, thanks.');const after=await state();assert(after.selected==='good'&&after.response.result===null&&after.queuedCount===before.queuedCount,'Selection submitted');assert(await page.locator('.option[aria-pressed="true"]').innerText()==='I’m good, thanks.','No selected distinction');await click('Submit');await has('Saved on device');assert((await state()).syncState!=='synced','Local result called canonical')});
add('QA-LRN-006',async()=>{await retrieve();await click('Go to school.');await click('Submit');await has('Not quite.','first response is preserved');await click('Try once more');await click('I’m good, thanks.');await click('Submit');await has('Correct.','Practice retry','first response remains unchanged');const s=await state();assert(s.response.first==='go'&&s.response.retry==='good','First response rewritten');extra.push(s.response)});
add('QA-LRN-007',async()=>{await retrieve();for(let i=0;i<2;i++){await click('Go to school.');await click('Submit');await has('Not quite.');if(!i)await click('Try once more')}assert(await btn('Try once more').count()===0,'Unlimited retry');await has('No more practice retries');assert((await state()).response.retryCount===1,'Retry counter');extra.push((await state()).response)});
add('QA-LRN-008 QA-BIZ-004',async()=>{await summary(true);await has('used assistance');extra.push(await state())});
add('QA-LRN-009 QA-BIZ-003',async()=>{await retrieve();await click('Skip for now');await has('Skipped for now.','no completion/mastery claim');assert((await state()).response.skipped,'Skip not recorded');await click('Continue');await has('Transfer')});
add('QA-LRN-010',async()=>{await retrieve();await click('I’m good, thanks.');await click('Submit');await has('Correct.');assert(!/mastered|level up/i.test(await text()),'Overclaim')});
add('QA-LRN-011',async()=>{await retrieve();await has('How are you?');await answer('I’m good, thanks.');await has('Transfer','classmate in the morning');assert(!/level.up/i.test(await text()),'Level-up copy')});
add('QA-LRN-013',async()=>{await checkStep();await has('Check');assert(await btn('Need a hint?').count()===0&&await btn('Skip for now').count()===0&&await btn('Submit').isDisabled(),'Check policy')});
add('QA-LRN-014 QA-BIZ-005',async()=>{await checkStep('listening');await has('Offered plays: 0 / 2','does not prove physical listening or authorize scoring');await click('▶ Play audio');await click('▶ Play audio');assert(await btn('▶ Play audio').isDisabled(),'Third play offered');await has('Offered plays: 2 / 2')});
add('QA-LRN-015',async()=>{await click('Start learning');await click('Skip for now');await click('Start without it');await has('provisional','Not enough evidence yet');await click('Go to Home');await has('Start cycle')});
add('QA-LRN-016',async()=>{await click('Start learning');await click('Everyday conversation');await click('Continue');await click('Take placement');for(const choice of ['Hello','She is here.','Good morning']){assert(await btn('Submit').isDisabled(),'Blank placement');if(choice==='Good morning')await click('▶ Play audio');await click(choice);await click('Submit');await click('Next')}await has('Your starting point is provisional','No certified CEFR score','Some starting evidence');extra.push(await state())});
add('QA-LRN-017',async()=>{await home();await click('Profile');await click('Edit goal');await click('Everyday conversation');await click('Save goal');await has('conversation','Your learning evidence');await click('Edit goal');await click('Clear goal');await has('Not set')});
add('QA-LRN-018 QA-BIZ-007',async()=>{await home();await click('Course');const before=await state();await click('Preview');await has('Preview does not create evidence','Prerequisite remains required');await page.keyboard.press('Tab');assert(await page.evaluate(()=>document.activeElement.closest('dialog')!==null),'Modal focus escaped');await page.keyboard.press('Escape');await page.waitForTimeout(30);assert(await page.getByTestId('action-L-042-preview').evaluate(e=>e===document.activeElement),'Preview focus restore');assert((await state()).queuedCount===before.queuedCount,'Preview created progress');await has('Locked · preview available')});
add('QA-LRN-019 QA-BIZ-014',async()=>{await home();await click('No recommendation');await has('Recommendation is unavailable');await click('Browse eligible cycles');await page.getByTestId('action-L-020-start-vocabulary').click();await click('Begin');await answer('Hello');await has('Learn')});
add('QA-LRN-020',async()=>{await home();await click('Nothing due');await has('Nothing eligible right now','does not mean you have completed or mastered');await click('Browse course');await has('Your path')});
add('QA-LRN-021',async()=>{await begin();assert(await btn('Submit').isDisabled(),'Blank review');await answer('Hello');await click('Continue');await answer('I’m good, thanks.');assert(await btn('Submit').isDisabled(),'Blank transfer');await answer('Good morning!');await click('Start Check');assert(await btn('Submit').isDisabled(),'Blank Check');assert((await state()).cycleStep===6,'Fake summary');await has('Check')});
add('QA-LRN-022',async()=>{await checkStep('grammar',true);await has('I ___ ready.');assert(await btn('Submit').isDisabled()&&await btn('Need a hint?').count()===0,'Grammar Check');await answer('am');await has('Grammar: review, learn, retrieve, transfer and independent Check.','used assistance')});
add('QA-LRN-023',async()=>{await begin('listening');for(let i=0;i<3;i++)await click('▶ Play audio');await has('Playback requests: 3');await answer('Hello');await click('Continue');await answer('I’m good, thanks.');await answer('Good morning!');await click('Start Check');await click('▶ Play audio');await click('▶ Play audio');assert(await btn('▶ Play audio').isDisabled(),'Check cap');await click('Simulate offline');await has('Required audio is unavailable offline','No result is created');assert(await btn('Submit').count()===0,'Missing media allows submit');await click('Simulate offline');await answer('Nice to meet you too.');await has('Done for now')});
add('QA-STF-001',async()=>{await staff();await has('Operational shell with mock data only','Content awaiting review','No production risk/analytics values')});
add('QA-STF-002 QA-STF-003',async()=>{await staff('Learners');await has('Learning evidence','Recent activity');await btn('Open').first().click();await has('Learning evidence','Engagement','Uncertainty','No precise mastery percentage','require server-side assigned-learner authorization');assert(!/diagnos|depressed|anxious/i.test(await text()),'Diagnosis copy')});
add('QA-STF-004 QA-STF-011',async()=>{await editor();await page.getByLabel('Prompt',{exact:true}).fill('Choose a friendly greeting.');await page.getByLabel('Correct answer',{exact:true}).fill('Hi');await click('Save draft');assert(await page.getByLabel('Prompt',{exact:true}).inputValue()==='Choose a friendly greeting.','Lost saved draft');await click('Preview');await has('Choose a friendly greeting.','Hi');await click('← Editor');await click('Submit for review');assert(await btn('Approve').isDisabled(),'Missing license bypass');await click('Open source & license');await page.getByLabel('Source reference').fill('Original demo author');await click('Mark verified for prototype');await click('Approve');await has('immutable revision');await click('Confirm publish');await has('Revision 4','Choose a friendly greeting.','Hi');await click('Create new draft from revision');await has('Draft 5');assert(await page.getByLabel('Correct answer',{exact:true}).inputValue()==='Hi','New draft lost lineage')});
add('QA-STF-005 QA-BIZ-012',async()=>{await publish();await has('Immutable published revision','Historical attempts stay pinned');assert(await page.locator('#app input,#app textarea').count()===0,'Published editable');assert(await btn('Edit').count()===0,'Published edit action');await click('Create new draft from revision');await has('Draft 5');assert(await page.getByLabel('Prompt',{exact:true}).isEditable(),'New draft not editable')});
add('QA-STF-006',async()=>{await review();await has('Needs confirmation','Publish remains blocked');assert(await btn('Approve').isDisabled(),'Unlicensed approval');await click('Open source & license');await has('Publicly accessible','not treated as permission to reuse')});
add('QA-STF-007',async()=>{await approve();await has('Publishing creates an immutable revision');for(const key of ['Tab','Tab','Shift+Tab']){await page.keyboard.press(key);assert(await page.evaluate(()=>document.activeElement.closest('dialog')!==null),'Modal focus escape')}await page.keyboard.press('Escape');await page.waitForTimeout(30);assert(await page.getByTestId('action-S-035-approve').evaluate(e=>e===document.activeElement),'Publish focus restoration');await click('Approve');await click('Cancel');await page.waitForTimeout(30);assert(await page.getByTestId('action-S-035-approve').evaluate(e=>e===document.activeElement),'Cancel restore')});
add('QA-STF-008 QA-BIZ-013',async()=>{await staff('Interventions');await has('Decision → Exposure → Execution → Outcome stay distinct','Domain implementation belongs to later phases')});
add('QA-STF-009',async()=>{await staff('Analytics');await has('definition, time window and source context','Domain implementation belongs to later phases')});
add('QA-STF-010',async()=>{await staff('Administration');await has('server-side authorization','later phases')});
add('QA-OFF-001',async()=>{await home();await click('Simulate offline');await has('You’re offline','Device-saved actions are not server-confirmed');await click('Start cycle');await click('Begin');await answer('Hello');await has('Learn')});
add('QA-OFF-002 QA-OFF-007',async()=>{await syncQueued();await has('Saved on this device','not server-confirmed');assert((await state()).syncState==='local_queued','Connectivity == synced');await click('Start sync');assert((await state()).syncState==='syncing','No syncing state');await has('not confirmation yet');await click('Simulate server acknowledgement');assert((await state()).syncState==='synced'&&(await state()).queuedCount===0,'Ack transition');await has('All caught up')});
add('QA-OFF-003',async()=>{await syncQueued();const count=(await state()).queuedCount;await click('Start sync');await click('Simulate failure');await has('same durable command identity','do not re-enter duplicate answers');await click('Retry safely');assert((await state()).queuedCount===count,'Retry duplicated actions');await click('Simulate partial');await has('Some work is still pending');await click('Sync remaining');await click('Simulate server acknowledgement');await has('All caught up')});
add('QA-OFF-004',async()=>{await syncQueued();await click('Canonical refresh');await has('do not overwrite it locally');await click('Refresh canonical state');await has('All caught up');assert((await state()).queuedCount===0,'Canonical refresh failed')});
add('QA-OFF-005',async()=>{await checkStep('listening');await click('Simulate offline');await has('Required audio is unavailable offline','No result is created');assert(await btn('Submit').count()===0,'Check completed with missing media');await click('Leave cycle');await has('Choose a representative cycle')});
add('QA-OFF-006',async()=>{await syncQueued();const count=(await state()).queuedCount;await click('Re-auth');await has('Sign in again','local queue is preserved');await click('Simulate re-auth complete');assert((await state()).queuedCount===count&&(await state()).syncState==='local_queued','Reauth authorized queue')});
add('QA-BIZ-009',async()=>{await home();await has('Streak shows study activity, not skill level.','Today’s target');await click('Profile');await has('learning evidence');assert(!/streak.*mastered/i.test(await text()),'Streak mastery')});
add('QA-ACC-001',async()=>{await staff();await page.locator('#surfaceStaff').focus();const visited=[];for(let i=0;i<28;i++){await page.keyboard.press(i<24?'Tab':'Shift+Tab');const v=await page.evaluate(()=>({text:document.activeElement.textContent,outline:getComputedStyle(document.activeElement).outlineStyle}));visited.push(v)}extra.push(visited);for(const title of ['Dashboard','Learners','Content','Interventions','Analytics','Administration'])assert(visited.some(v=>v.text===title&&v.outline==='solid'),'Unreachable/unfocused '+title);await btn('Content').focus();await page.keyboard.press('Enter');await has('Content library');await btn('Create draft').focus();await page.keyboard.press('Enter');await has('Draft 4')});
add('QA-ACC-002',async()=>{await retrieve();await page.locator('.page-title').focus();await page.keyboard.press('Tab');assert(await btn('I’m good, thanks.').evaluate(e=>e===document.activeElement),'Wrong first option focus');await page.keyboard.press('Enter');assert(await btn('I’m good, thanks.').evaluate(e=>e===document.activeElement),'Selection lost focus');await page.keyboard.press('Tab');assert(await btn('Go to school.').evaluate(e=>e===document.activeElement),'Wrong next option');assert(await page.locator('main[aria-live]').count()===0,'Whole page live region');assert(await page.locator('#liveStatus').getAttribute('aria-live')==='polite','No targeted live region');await click('Need a hint?');await page.waitForTimeout(30);assert((await page.locator('#liveStatus').innerText()).includes('Hint used'),'No hint announcement')});
add('QA-ACC-003',async()=>{await begin();const sizes=await page.locator('#app button').evaluateAll(es=>es.filter(e=>e.getClientRects().length).map(e=>({name:e.textContent,w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})));extra.push(sizes);assert(sizes.every(s=>s.w>=48&&s.h>=48),'Target smaller than 48 CSS px');await homeReload();const nav=await page.locator('.bottom-nav button').evaluateAll(es=>es.map(e=>({w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})));assert(nav.every(s=>s.w>=48&&s.h>=48),'Small bottom target')});
async function homeReload(){await page.reload();await home()}
add('QA-ACC-005',async()=>{await reflow(360,'Profile',true)});
add('QA-ACC-006',async()=>{await context.emulateMedia?.({reducedMotion:'reduce'});await page.emulateMedia({reducedMotion:'reduce'});await home();extra.push(await page.evaluate(()=>({reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,animation:getComputedStyle(document.querySelector('.btn')).animationName})));assert(extra.at(-1).reduced&&extra.at(-1).animation==='none','Reduced motion ignored')});
add('QA-ACC-007 QA-ACC-013',async()=>{await editor();let tree=await ax();for(const name of ['Prompt','Correct answer','Feedback','Source / license','Item type','Domain'])assert(tree.some(n=>n.name===name&&['textbox','combobox'].includes(n.role)),'Missing AX name '+name);extra.push({screen:'editor',tree});await click('Submit for review');await click('Open source & license');tree=await ax();for(const name of ['Source reference','Reuse permission'])assert(tree.some(n=>n.name===name),'Missing AX name '+name);extra.push({screen:'source-license',tree});});
add('QA-ACC-008',async()=>{await editor();await page.getByLabel('Prompt',{exact:true}).fill('');await click('Save draft');await has('Prompt and correct answer are required.');assert(await page.getByRole('alert').count()===1,'Error not text/alert');await click('Submit for review');await has('Draft 4')});
add('QA-ACC-009',async()=>{for(const route of ['Home','Learn','Profile']){await page.reload();await reflow(360,route)}});
add('QA-ACC-010',async()=>{for(const route of ['Home','Learn','Course','Profile']){await page.reload();await reflow(480,route)}});
add('QA-ACC-011 QA-ACC-012',async id=>{const w=id==='QA-ACC-011'?1440:1024;await page.setViewportSize({width:w,height:1000});await staff();await has('Dashboard');await click('Content');await has('Content library','Draft','Published');const size=await page.evaluate(()=>({w:innerWidth,scroll:document.documentElement.scrollWidth,main:document.querySelector('.staff-main').getBoundingClientRect().width}));extra.push(size);assert(size.scroll<=w+1&&size.main>600,'Staff unusable width')});

(async()=>{
 const browser=await chromium.launch({executablePath:process.env.MINGO_CHROME||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 const results=[];const priority=process.env.MINGO_QA_PRIORITY;const ordered=cases.filter(c=>tests[c.id]&&(!priority||c.priority===priority)).sort((a,b)=>a.priority.localeCompare(b.priority));
 for(const c of ordered){context=await browser.newContext({viewport:{width:1440,height:1000}});page=await context.newPage();page.setDefaultTimeout(4500);log=[];extra=[];const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));const started=new Date().toISOString();let status='PASS',failure=null;
  try{const prototypeUrl=process.env.MINGO_PROTOTYPE_URL||'http://127.0.0.1:8765/';await page.goto(prototypeUrl);await tests[c.id](c.id);assert(errors.length===0,'JS errors '+errors.join(';'));assert(requests.every(u=>u.startsWith(new URL(prototypeUrl).origin+'/')),'External dependency request')}catch(e){status='FAIL';failure=e.message}
  const evidence={id:c.id,priority:c.priority,status,started,ended:new Date().toISOString(),expected:c.expected,steps:log,observed:await text().catch(()=>''),state:await state().catch(()=>null),extra,errors,requests,failure};
  fs.writeFileSync(path.join(out,c.id+'.json'),JSON.stringify(evidence,null,2));await page.screenshot({path:path.join(out,c.id+'.png'),fullPage:true});results.push({id:c.id,status,failure,evidence:path.join(out,c.id+'.json').replaceAll('\\','/')});console.log(c.id+' '+status+(failure?' '+failure.slice(0,180):''));await context.close();
 }
 fs.writeFileSync(path.join(out,priority?`run-${priority}.json`:'run.json'),JSON.stringify({browser:browser.version(),freshContextPerCase:true,headless:true,results,prototype_files_sha256:Object.fromEntries(['app.js','index.html','styles.css'].map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync('02_Tai_lieu_du_an/04_Thiet_ke_san_pham/ux_ui/phase2/prototype/'+f)).digest('hex')]))},null,2));await browser.close();process.exitCode=results.some(r=>r.status!=='PASS')?1:0;
})();
